name: Gradle Test

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
#        with:
#          add-job-summary: 'never'

      - run: ./gradlew lint
        env:
          GRADLE_OPTS: '-Dorg.gradle.caching=true'
