name: Junit Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
#      - uses: yumemi-inc/setup-java-gradle@v1

      - uses: MobSF/mobsfscan@0.3.6
        with:
          args: . --sarif --output '${{ runner.temp }}/mobsfscan-results.sarif'
        continue-on-error: true
      - uses: reviewdog/action-setup@v1
      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -f=sarif -reporter=github-check -name='mobsfscan' -filter-mode=nofilter < '${{ runner.temp }}/mobsfscan-results.sarif'
