name: Analysis Report

on:
  push:
    branches: [main]

#concurrency:
#  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      checks: write # for reviewdog
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }} # jobへ定義してしまう
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - uses: reviewdog/action-setup@v1
      - run: ./gradlew androidApp:lintDebug --continue
        continue-on-error: true
      - run: |
          find . -regex '^.*/build/reports/lint-results.*\.sarif$' -type f | while read file_path; do
            reviewdog -f=sarif -reporter=github-check -name='Android Lint' < "$file_path"
          done
      - run: ./gradlew ktlintCheck --continue
        continue-on-error: true
      - run: |
          find . -regex '^.*/build/reports/ktlint-results\.sarif$' -type f | while read file_path; do
            module="$(echo "$file_path" | awk '{gsub(/^\.\/|\/build\/.*$/,"")}1')"
            reviewdog -f=sarif -reporter=github-check -name="ktlint(${module})" < "$file_path"
          done
      - uses: MobSF/mobsfscan@0.3.6
        with:
          args: . --sarif --output '${{ runner.temp }}/mobsfscan-results.sarif'
        continue-on-error: true
      - run: reviewdog -f=sarif -reporter=github-check -name='mobsfscan' < '${{ runner.temp }}/mobsfscan-results.sarif'

      - run: gh api repos/{owner}/{repo}/commits/${{ github.sha }}/check-runs | jq .check_runs[].conclusion
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          failure_count=$(gh api repos/{owner}/{repo}/commits/${{ github.sha }}/check-runs | jq '.check_runs|map(select(.conclusion=="failure"))|length')
          echo $failure_count

        env:
          GH_TOKEN: ${{ github.token }}
