name: Junit Test

on: push

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v1
        wit:
          cache-read-only: false

      - run: ./gradlew test
