name: Analysis Report

on:
  push:
    branches: [main]

#concurrency:
#  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#  cancel-in-progress: true

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      checks: write # for reviewdog
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }} # jobへ定義してしまう
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
      - uses: reviewdog/action-setup@v1
      - run: ./gradlew androidApp:lintDebug --continue
        continue-on-error: true
        id: android-lint
      - run: |
          find . -regex '^.*/build/reports/lint-results.*\.sarif$' -type f | while read file_path; do
            reviewdog -f=sarif -reporter=github-check -name='Android Lint' -fail-on-error=true < "$file_path"
          done
      - run: ./gradlew ktlintCheck --continue
        continue-on-error: true
        id: ktlint
      - run: |
          find . -regex '^.*/build/reports/ktlint-results\.sarif$' -type f | while read file_path; do
            module="$(echo "$file_path" | awk '{gsub(/^\.\/|\/build\/.*$/,"")}1')"
            jq '.runs[].results[].level = "warning"' < "$file_path" | \
              reviewdog -f=sarif -reporter=github-check -name="ktlint(${module})" -fail-on-error=true
          done
      - uses: MobSF/mobsfscan@0.3.6
        with:
          args: . --sarif --output '${{ runner.temp }}/mobsfscan-results.sarif'
        continue-on-error: true
        id: mobsfscan
      - run: reviewdog -f=sarif -reporter=github-check -name='mobsfscan' -fail-on-error=true < '${{ runner.temp }}/mobsfscan-results.sarif'
