name: Android Lint Report

on:
  push:
    branches: [main]

concurrency: # deploy 中の job が既にあれば待つ
  group: 'github-pages' # 名前はなんでもよい
  cancel-in-progress: false

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      pages: write # for pages action
      id-token: write # for pages action
    environment: # 必ずしも deployment イベントを発行する必要はないがリポジトリ TOP から遷移しやすいので
      name: 'github-pages' # 名前はなんでもよい
      url: ${{steps.deploy.outputs.page_url}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew androidApp:lintDebug --continue
        continue-on-error: true
      - run: |
          mkdir '${{ runner.temp }}/reports'
          cp ./androidApp/build/reports/lint-results-debug.html '${{ runner.temp }}/reports/index.html'
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ runner.temp }}/reports
      - uses: actions/deploy-pages@v4
        id: deploy
