name: Junit Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # for dorny/test-reporter checks
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v1
      - run: ./gradlew test --continue
        id: test
      #- if: failure() && steps.test.outcome == 'failure'
      - if: cancelled() != true
        uses: dorny/test-reporter@v1
        with:
          name: 'JUnit Test Report'
          path: '**/build/test-results/*/TEST-*.xml'
          reporter: 'java-junit'
          fail-on-error: false
          #list-suites: 'failed'
