name: Junit Test

on: pull_request

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # for action-junit-report action
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v1
        with:
          cache-read-only: false

      - run: ./gradlew test --continue
        id: test

      - if: failure() && steps.test.outcome == 'failure'

#        uses: mikepenz/action-junit-report@v3
#        with:
#          report_paths: '**/build/test-results/*/TEST-*.xml'
#          annotate_only: true


        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/build/test-results/*/TEST-*.xml'



#        uses: dorny/test-reporter@v1
#        with:
#          name: 'JUnit Test Report'
#          path: '**/build/test-results/*/TEST-*.xml'
#          reporter: 'java-junit'
#          fail-on-error: false
#          list-suites: 'failed'
