name: Junit Test

on: push

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: yumemi-inc/setup-java-gradle@v1
        with:
          cache-read-only: false

      - run: ./gradlew test
        id: test

        if: failure() && steps.test.outcome == 'failure'
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          annotate_only: true
