name: Matcher Test

on: push

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          repository: google/iosched
          path: sample

      - run: echo '::add-matcher::./main/.github/workflows/kotlin.json'

      - name: Build
        run: |
          cd sample
          ./gradlew assembleDebug
