name: Matcher Test

on: push

jobs:
  matcher-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
#        with:
#          path: main
#      - uses: actions/checkout@v4
#        with:
#          repository: google/iosched
#          path: sample

      - run: echo '::add-matcher::./.github/workflows/kotlin.json'

      - run: |
          echo "w: /home/runner/work/android-ci-test/android-ci-test/androidApp/src/main/java/com/example/myhandsonapplication/android/MainActivity.kt: (35, 5): Parameter 'configSettings' is never used"

#      - name: Build
#        run: |
#          cd sample
#          ./gradlew assembleDebug
